server:
  port: 10001

spring:
  application:
    name: student-server
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sutdent?useUnicode=true&character=UTF-8&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
#    mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  mapper-locations: classpath:mappers/*Mapper.xml

eureka:
  client:
    service-url:
      defaultZone: http://192.168.31.159:8100/eureka/,http://192.168.31.159:9100/eureka/
    register-with-eureka: true
    fetch-registry: true
