server:
  port: 10002

spring:
  application:
    name: log-server
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud?useUnicode=true&character=UTF-8&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: 192.168.31.159
    port: 5672
    username: admin
    password: admin
    virtual-host: testhost

eureka:
  client:
    service-url:
      defaultZone: http://192.168.31.159:8100/eureka/,http://192.168.31.159:9100/eureka/
    register-with-eureka: true
    fetch-registry: true

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true